"""
CausIQ :: Synthetic Source Generator with Planted Ground Truth
==============================================================

WHY THIS EXISTS
---------------
A KPI root-cause engine can only be evaluated if you already know the answer.
Real enterprise data never comes with a label saying "the checkout release cost
you 3.5% of revenue". So we *plant* the causes, then check whether the engine
recovers them.

HOW GROUND TRUTH IS DEFINED
---------------------------
Revenue is generated by an explicit structural model:

    sessions   = base x seasonality x trend x PROD(shock session multipliers) x noise
    conversion = base x seasonality       x PROD(shock conversion multipliers) x noise
    aov        = base                     x PROD(shock aov multipliers)        x noise
    revenue    = sessions x conversion x aov

Each "shock" is a real-world event (a release, a stockout, a competitor promo).
Because the model is multiplicative, effects interact — so the contribution of
any single shock depends on which others are present. We therefore define the
ground-truth contribution of each shock as its **Shapley value** over the set
of all shocks: the average marginal effect across every possible subset.

Shapley values are the unique attribution that is efficient (they sum exactly
to the total effect), symmetric, and order-independent. With 5 shocks we
enumerate all 2^5 = 32 counterfactual worlds exhaustively — no approximation.

Critically, the noise arrays are drawn ONCE and held fixed across all 32
counterfactual runs. Toggling a shock therefore changes the outcome only
through that shock's own causal pathway, never through resampled randomness.

THE TRAP (deliberate)
---------------------
`in_stock_rate` and `competitor_price` reduce BOTH sessions and conversion.
So a large part of the session decline is *mediated*, not exogenous. An engine
that ranks drivers by correlation with revenue will blame the marketing budget
cut, because traffic tracks revenue almost perfectly. The causally correct
answer ranks the checkout release first and marketing last. Getting this wrong
costs Rs 60L/month in paid spend poured into a broken funnel.

Run:  python -m causiq.ingest.generate
"""

from __future__ import annotations

import itertools
import json
import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import least_squares

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

SEED = 20260827
RNG = np.random.default_rng(SEED)

DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "raw"
DATA_DIR.mkdir(parents=True, exist_ok=True)

HISTORY_START = pd.Timestamp("2024-01-01")
TODAY = pd.Timestamp("2026-08-27")
HISTORY_END = pd.Timestamp("2026-08-26")

# The KPI movement under investigation: EU, week of Mon 17 Aug - Sun 23 Aug 2026
ANALYSIS_START = pd.Timestamp("2026-08-17")
ANALYSIS_END = pd.Timestamp("2026-08-23")
ANALYSIS_REGION = "EU"

REGIONS = ["EU", "US", "APAC", "IN"]
CHANNELS = ["web", "app"]
DEVICES = ["desktop", "mobile"]

# Wearables is deliberately a new launch -> sparse history scenario
CATEGORIES = ["Electronics", "Accessories", "Home", "Apparel", "Wearables"]
WEARABLES_LAUNCH = pd.Timestamp("2026-07-13")
WEARABLES_REGIONS = ["EU", "IN"]

# Base weekly scale per region: tuned so EU weekly net revenue ~ Rs 10.0 Cr
REGION_SCALE = {"EU": 1.00, "US": 0.86, "APAC": 0.41, "IN": 0.63}

CATEGORY_MIX = {
    "Electronics": 0.42,
    "Accessories": 0.16,
    "Home": 0.21,
    "Apparel": 0.18,
    "Wearables": 0.03,
}

# AOV in INR by category
CATEGORY_AOV = {
    "Electronics": 18400.0,
    "Accessories": 2150.0,
    "Home": 6400.0,
    "Apparel": 3100.0,
    "Wearables": 9800.0,
}

CATEGORY_CVR = {
    "Electronics": 0.0212,
    "Accessories": 0.0385,
    "Home": 0.0248,
    "Apparel": 0.0301,
    "Wearables": 0.0164,
}

CATEGORY_MARGIN = {
    "Electronics": 0.223,
    "Accessories": 0.412,
    "Home": 0.318,
    "Apparel": 0.376,
    "Wearables": 0.281,
}

CHANNEL_SPLIT = {"web": 0.58, "app": 0.42}

# -----------------------------------------------------------------------------
# Target ground-truth contributions for the EU analysis week,
# expressed as % of expected (unshocked) net revenue.
# The generator SOLVES for shock strengths that produce exactly these.
# -----------------------------------------------------------------------------

TARGET_CONTRIB_PCT = {
    "checkout_deploy": -3.60,
    "stockout": -2.40,
    "competitor_promo": -1.90,
    "marketing_cut": -1.10,
    "accessories_promo": +1.00,
}
# Sums to exactly -8.00%, matching the headline movement.
#
# Note there is no "unexplained" term here by construction: because the noise
# arrays are held fixed, the expected (no-shock) world already contains the same
# noise realisation as the actual world, so Shapley values sum exactly to the
# observed gap. Residual error appears where it honestly belongs -- on the
# ENGINE side, whose forecast baseline is an estimate rather than the true
# counterfactual, and whose recovered contributions will therefore differ from
# these figures by a measurable amount. That difference is the accuracy metric.

SHOCK_NAMES = list(TARGET_CONTRIB_PCT.keys())


# -----------------------------------------------------------------------------
# Shock definitions
# -----------------------------------------------------------------------------

@dataclass
class Shock:
    """A real-world event with a causal pathway onto sessions / cvr / aov.

    `strength` is solved numerically so the resulting Shapley contribution
    matches the target above. `w_*` weights split the effect across pathways
    and encode the mediation structure declared in the KPI contract's DAG.
    """
    name: str
    label: str
    start: pd.Timestamp
    end: pd.Timestamp
    regions: list[str]
    categories: list[str] | None      # None = all categories
    w_sessions: float = 0.0
    w_cvr: float = 0.0
    w_aov: float = 0.0
    sign: float = -1.0                # -1 depresses, +1 lifts
    strength: float = 0.05

    def active(self, dates: pd.DatetimeIndex, region: str, category: str) -> np.ndarray:
        if region not in self.regions:
            return np.zeros(len(dates), dtype=float)
        if self.categories is not None and category not in self.categories:
            return np.zeros(len(dates), dtype=float)
        return ((dates >= self.start) & (dates <= self.end)).astype(float)

    def multipliers(self, dates, region, category) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        a = self.active(dates, region, category)
        s = self.sign * self.strength
        return (
            1.0 + a * s * self.w_sessions,
            1.0 + a * s * self.w_cvr,
            1.0 + a * s * self.w_aov,
        )


def build_shocks() -> dict[str, Shock]:
    """The five planted events.

    Note the mediation weights: `stockout` and `competitor_promo` push on BOTH
    sessions and conversion. That is what makes a session decline partly an
    *effect* of those drivers rather than an independent cause — the confound
    the CHALLENGE stage has to untangle.
    """
    return {
        "checkout_deploy": Shock(
            name="checkout_deploy",
            label="Checkout redesign v4.2 shipped to EU only",
            start=pd.Timestamp("2026-08-12"),
            end=HISTORY_END,
            regions=["EU"],                 # US and APAC stay on v4.1 -> control group
            categories=None,
            w_sessions=0.0,                 # a checkout bug cannot reduce site traffic
            w_cvr=1.0,
            sign=-1.0,
        ),
        "stockout": Shock(
            name="stockout",
            label="Hero SKU stockout, EU fulfilment centres",
            start=pd.Timestamp("2026-08-19"),
            end=pd.Timestamp("2026-08-23"),
            regions=["EU"],
            categories=["Electronics"],
            # Most of a stockout's damage arrives through LOST TRAFFIC, not just
            # lost conversion: dead product pages fall out of organic ranking and
            # get pulled from retargeting, so shoppers never arrive at all. That
            # majority-traffic split is what makes sessions a mediator rather
            # than an independent driver, and it is the crux of the whole case.
            w_sessions=0.55,
            w_cvr=0.45,
            sign=-1.0,
        ),
        "competitor_promo": Shock(
            name="competitor_promo",
            label="Competitor 12% price cut on comparable SKUs",
            start=pd.Timestamp("2026-08-15"),
            end=pd.Timestamp("2026-08-26"),
            regions=["EU", "US"],
            categories=["Electronics", "Wearables"],
            w_sessions=0.52,                # their ads pull our shoppers away
            w_cvr=0.48,
            sign=-1.0,
        ),
        "marketing_cut": Shock(
            name="marketing_cut",
            label="Planned 30% paid acquisition budget reduction, EU",
            start=pd.Timestamp("2026-08-10"),
            end=HISTORY_END,
            regions=["EU"],
            categories=None,
            w_sessions=1.0,                 # purely a traffic lever
            w_cvr=0.0,
            sign=-1.0,
        ),
        "accessories_promo": Shock(
            name="accessories_promo",
            label="Accessories bundle promotion, EU",
            start=pd.Timestamp("2026-08-14"),
            end=pd.Timestamp("2026-08-24"),
            regions=["EU"],
            categories=["Accessories"],
            w_sessions=0.0,
            w_cvr=0.88,                     # promo lifts conversion strongly
            w_aov=-0.26,                    # partially offset by a cheaper basket
            sign=+1.0,
        ),
    }


# -----------------------------------------------------------------------------
# Deterministic base signal + fixed noise
# -----------------------------------------------------------------------------

@dataclass
class Panel:
    """Pre-computed deterministic signal and FIXED noise for one series.

    Fixing the noise is what makes counterfactual toggling valid: switching a
    shock off changes the outcome only through that shock's causal pathway.
    """
    dates: pd.DatetimeIndex
    region: str
    category: str
    channel: str
    base_sessions: np.ndarray
    base_cvr: np.ndarray
    base_aov: np.ndarray
    noise_sessions: np.ndarray = field(repr=False, default=None)
    noise_cvr: np.ndarray = field(repr=False, default=None)
    noise_aov: np.ndarray = field(repr=False, default=None)


def _seasonality(dates: pd.DatetimeIndex) -> np.ndarray:
    doy = dates.dayofyear.values.astype(float)
    dow = dates.dayofweek.values.astype(float)
    annual = 1.0 + 0.16 * np.sin(2 * np.pi * (doy - 45) / 365.25)
    weekly = 1.0 + 0.13 * np.sin(2 * np.pi * (dow - 1.5) / 7.0)
    # Festive lift: Indian festive season and EU Black Friday window
    festive = np.where((doy > 285) & (doy < 320), 1.22, 1.0)
    return annual * weekly * festive


def _cvr_seasonality(dates: pd.DatetimeIndex) -> np.ndarray:
    dow = dates.dayofweek.values.astype(float)
    return 1.0 + 0.06 * np.cos(2 * np.pi * (dow - 3.0) / 7.0)


def build_panels() -> list[Panel]:
    dates = pd.date_range(HISTORY_START, HISTORY_END, freq="D")
    n = len(dates)
    trend = np.linspace(1.0, 1.34, n)          # steady growth over 2.6 years
    seas = _seasonality(dates)
    cvr_seas = _cvr_seasonality(dates)

    panels: list[Panel] = []
    for region in REGIONS:
        for category in CATEGORIES:
            if category == "Wearables" and region not in WEARABLES_REGIONS:
                continue
            for channel in CHANNELS:
                # Calibrated so EU weekly net revenue lands near Rs 10.0 Cr
                scale = (
                    317_000
                    * REGION_SCALE[region]
                    * CATEGORY_MIX[category]
                    * CHANNEL_SPLIT[channel]
                )
                base_sessions = scale * trend * seas / 7.0
                base_cvr = np.full(n, CATEGORY_CVR[category]) * cvr_seas
                base_aov = np.full(n, CATEGORY_AOV[category])

                if category == "Wearables":
                    # Newly launched: nothing before launch date, plus a steep
                    # early-life ramp that no seasonal model can extrapolate.
                    live = (dates >= WEARABLES_LAUNCH).astype(float)
                    weeks_live = np.clip(
                        (dates - WEARABLES_LAUNCH).days.values / 7.0, 0, None
                    )
                    ramp = 1.0 - 0.55 * np.exp(-weeks_live / 3.2)
                    base_sessions = base_sessions * live * ramp
                    base_cvr = base_cvr * (0.72 + 0.28 * (1 - np.exp(-weeks_live / 4.0)))
                    # Early-life volatility. NOT a planted driver and therefore
                    # outside the Shapley set: a brand-new category swings hard
                    # week to week for reasons no model can attribute yet. This
                    # is what the sparse-history scenario has to resist
                    # over-explaining -- it looks like a 15% collapse, but with
                    # five weeks of history it is not distinguishable from the
                    # launch period's own noise.
                    dip = np.where(
                        (dates >= pd.Timestamp("2026-08-17"))
                        & (dates <= pd.Timestamp("2026-08-23")),
                        0.845, 1.0,
                    )
                    base_cvr = base_cvr * dip

                p = Panel(
                    dates=dates,
                    region=region,
                    category=category,
                    channel=channel,
                    base_sessions=base_sessions,
                    base_cvr=base_cvr,
                    base_aov=base_aov,
                )
                # Fixed noise, drawn once, reused across every counterfactual.
                # Calibrated to daily category-channel aggregates at this volume
                # (tens of thousands of sessions per cell), where relative noise
                # is genuinely low. Setting it higher would not make the demo
                # more honest, only less identifiable: the true session effects
                # here are 1-2%, and no estimator can separate those from 5%
                # daily noise on a three-week window.
                p.noise_sessions = RNG.normal(1.0, 0.012, n)
                p.noise_cvr = RNG.normal(1.0, 0.020, n)
                p.noise_aov = RNG.normal(1.0, 0.010, n)
                panels.append(p)
    return panels


# -----------------------------------------------------------------------------
# Counterfactual evaluation
# -----------------------------------------------------------------------------

def evaluate(panel: Panel, shocks: dict[str, Shock], active: set[str]) -> dict[str, np.ndarray]:
    """Evaluate one series under the subset `active` of shocks."""
    m_sess = np.ones(len(panel.dates))
    m_cvr = np.ones(len(panel.dates))
    m_aov = np.ones(len(panel.dates))

    for name in active:
        sh = shocks[name]
        a, b, c = sh.multipliers(panel.dates, panel.region, panel.category)
        m_sess *= a
        m_cvr *= b
        m_aov *= c

    sessions = panel.base_sessions * m_sess * panel.noise_sessions
    cvr = np.clip(panel.base_cvr * m_cvr * panel.noise_cvr, 1e-6, 0.65)
    aov = panel.base_aov * m_aov * panel.noise_aov
    orders = sessions * cvr
    revenue = orders * aov

    return {"sessions": sessions, "cvr": cvr, "aov": aov,
            "orders": orders, "revenue": revenue}


def window_revenue(panels: list[Panel], shocks: dict[str, Shock],
                   active: set[str], region: str,
                   start: pd.Timestamp, end: pd.Timestamp) -> float:
    """Total revenue in a region/date window under a given counterfactual."""
    total = 0.0
    for p in panels:
        if p.region != region:
            continue
        mask = (p.dates >= start) & (p.dates <= end)
        if not mask.any():
            continue
        total += float(evaluate(p, shocks, active)["revenue"][mask].sum())
    return total


def shapley_contributions(panels: list[Panel], shocks: dict[str, Shock],
                          region: str, start: pd.Timestamp,
                          end: pd.Timestamp) -> tuple[dict[str, float], float, float]:
    """Exact Shapley decomposition over all 2^5 counterfactual worlds.

    Returns (contribution_inr_by_shock, expected_revenue, actual_revenue).
    Contributions sum exactly to (actual - expected) by the efficiency axiom.
    """
    names = list(shocks.keys())
    k = len(names)

    # Pre-compute revenue for every subset — 32 evaluations, no approximation
    cache: dict[frozenset, float] = {}
    for r in range(k + 1):
        for combo in itertools.combinations(names, r):
            s = frozenset(combo)
            cache[s] = window_revenue(panels, shocks, set(s), region, start, end)

    contrib = {n: 0.0 for n in names}
    for n in names:
        others = [x for x in names if x != n]
        for r in range(len(others) + 1):
            weight = (math.factorial(r) * math.factorial(k - r - 1)) / math.factorial(k)
            for combo in itertools.combinations(others, r):
                s = frozenset(combo)
                contrib[n] += weight * (cache[s | {n}] - cache[s])

    expected = cache[frozenset()]
    actual = cache[frozenset(names)]
    return contrib, expected, actual


# -----------------------------------------------------------------------------
# Calibration: solve shock strengths to hit the target contributions
# -----------------------------------------------------------------------------

def calibrate(panels: list[Panel]) -> dict[str, Shock]:
    """Numerically solve for shock strengths hitting TARGET_CONTRIB_PCT.

    Because the model is multiplicative, a shock's Shapley contribution is not
    a simple function of its own strength — it depends on every other shock.
    So we solve the joint system rather than tuning constants by hand.
    """
    shocks = build_shocks()

    def residuals(x: np.ndarray) -> np.ndarray:
        for i, name in enumerate(SHOCK_NAMES):
            shocks[name].strength = float(abs(x[i]))
        contrib, expected, _ = shapley_contributions(
            panels, shocks, ANALYSIS_REGION, ANALYSIS_START, ANALYSIS_END
        )
        return np.array([
            100.0 * contrib[n] / expected - TARGET_CONTRIB_PCT[n]
            for n in SHOCK_NAMES
        ])

    x0 = np.array([0.14, 0.16, 0.10, 0.16, 0.09])
    sol = least_squares(residuals, x0, xtol=1e-8, ftol=1e-8, max_nfev=90)
    for i, name in enumerate(SHOCK_NAMES):
        shocks[name].strength = float(abs(sol.x[i]))
    return shocks


# -----------------------------------------------------------------------------
# Source table emission
# -----------------------------------------------------------------------------

def emit_sources(panels: list[Panel], shocks: dict[str, Shock]) -> dict[str, pd.DataFrame]:
    """Materialise the four heterogeneous sources from the true world state."""
    rows_sales, rows_web, rows_ops = [], [], []
    all_active = set(shocks.keys())

    for p in panels:
        out = evaluate(p, shocks, all_active)
        sessions, cvr, aov = out["sessions"], out["cvr"], out["aov"]
        orders, revenue = out["orders"], out["revenue"]

        live = sessions > 0
        margin = CATEGORY_MARGIN[p.category]

        # --- discount depth, incl. the Accessories promo and a margin shift ---
        disc = np.full(len(p.dates), 0.06)
        promo = shocks["accessories_promo"]
        disc += 0.09 * promo.active(p.dates, p.region, p.category)
        # A genuine input-cost increase in EU from Aug 18 — the ambiguity that
        # makes the gross-margin movement un-attributable (abstention scenario)
        cogs_shift = np.where(
            (p.dates >= pd.Timestamp("2026-08-18")) & (p.region == "EU"), 0.028, 0.0
        )

        cogs = revenue * (1.0 - margin + cogs_shift)

        # --- paid marketing spend, an observed and controllable regressor ----
        # Paid is a minority of traffic; the planned cut is 30% of paid spend,
        # which is a far smaller share of total sessions. That gap is exactly
        # why the naive read over-credits marketing.
        mk = shocks["marketing_cut"]
        spend_base = float(np.mean(p.base_sessions)) * 41.0     # INR per session
        paid_spend = spend_base * (
            1.0 - 0.30 * mk.active(p.dates, p.region, p.category)
        ) * (1.0 + 0.05 * np.sin(np.arange(len(p.dates)) / 9.0))

        for i, d in enumerate(p.dates):
            if not live[i]:
                continue
            rows_sales.append({
                "date": d.date(),
                "region": p.region,
                "category": p.category,
                "channel": p.channel,
                "orders": round(float(orders[i]), 2),
                "net_revenue_inr": round(float(revenue[i]), 2),
                "discount_inr": round(float(revenue[i] * disc[i]), 2),
                "cogs_inr": round(float(cogs[i]), 2),
                "aov_inr": round(float(aov[i]), 2),
                "paid_spend_inr": round(float(paid_spend[i]), 2),
            })

        # --- web_events: HOURLY grain, must be rolled up before joining ---
        # Only the trailing 120 days are kept hourly (realistic retention).
        hourly_from = HISTORY_END - pd.Timedelta(days=120)
        for i, d in enumerate(p.dates):
            if not live[i]:
                continue
            if d < hourly_from:
                rows_web.append({
                    "datetime_hour": pd.Timestamp(d) + pd.Timedelta(hours=12),
                    "region": p.region, "channel": p.channel,
                    "device": "all", "category": p.category,
                    "sessions": round(float(sessions[i]), 2),
                    "checkout_starts": round(float(orders[i] * 2.35), 2),
                    "checkout_errors": 0.0,
                })
                continue

            # Distribute the day across 24 hours with a diurnal curve
            hours = np.arange(24)
            curve = 1.0 + 0.55 * np.sin(2 * np.pi * (hours - 8) / 24.0)
            curve = curve / curve.sum()
            # Checkout error rate: baseline ~0.4%, spikes in EU post-release
            ck = shocks["checkout_deploy"]
            err_rate = 0.004 + 0.061 * float(ck.active(
                pd.DatetimeIndex([d]), p.region, p.category)[0])
            for h in hours:
                s_h = float(sessions[i] * curve[h])
                starts = s_h * float(cvr[i]) * 2.35
                rows_web.append({
                    "datetime_hour": pd.Timestamp(d) + pd.Timedelta(hours=int(h)),
                    "region": p.region, "channel": p.channel,
                    "device": DEVICES[h % 2], "category": p.category,
                    "sessions": round(s_h, 2),
                    "checkout_starts": round(starts, 2),
                    "checkout_errors": round(starts * err_rate, 3),
                })

    # --- ops_inventory: WEEKLY grain against a DAILY KPI ---
    stock = shocks["stockout"]
    weeks = pd.date_range(pd.Timestamp("2024-06-03"), HISTORY_END, freq="W-MON")
    for wk in weeks:
        wk_days = pd.date_range(wk, wk + pd.Timedelta(days=6), freq="D")
        for region in REGIONS:
            for category in CATEGORIES:
                if category == "Wearables":
                    if region not in WEARABLES_REGIONS or wk < WEARABLES_LAUNCH:
                        continue
                a = stock.active(wk_days, region, category).mean()
                in_stock = 0.947 - 0.31 * a + float(RNG.normal(0, 0.012))
                rows_ops.append({
                    "iso_week": wk.date(),
                    "region": region,
                    "category": category,
                    "in_stock_rate": round(float(np.clip(in_stock, 0.30, 1.0)), 4),
                    "days_of_cover": round(float(np.clip(21 - 12 * a
                                                         + RNG.normal(0, 1.4), 1, 40)), 2),
                    "landed_cogs_index": round(float(
                        1.0 + (0.031 if (region == "EU" and wk
                                         >= pd.Timestamp("2026-08-17")) else 0.0)
                        + RNG.normal(0, 0.004)), 4),
                })

    sales = pd.DataFrame(rows_sales)
    web = pd.DataFrame(rows_web)
    ops = pd.DataFrame(rows_ops)

    # --- Planted data-quality defect: 18% of EU discount values null from Aug 20
    # This is what pushes the gross-margin case below the coverage threshold.
    defect_mask = (
        (pd.to_datetime(sales["date"]) >= pd.Timestamp("2026-08-20"))
        & (sales["region"] == "EU")
    )
    idx = sales.index[defect_mask]
    drop = RNG.choice(idx, size=int(len(idx) * 0.18), replace=False)
    sales.loc[drop, "discount_inr"] = np.nan

    # --- ops_inventory is STALE: last successful load was Mon 17 Aug.
    # At TODAY (27 Aug) that is 240h old against a 180h SLA -> breach.
    ops = ops[pd.to_datetime(ops["iso_week"]) <= pd.Timestamp("2026-08-17")]

    return {"wh_sales": sales, "web_events": web, "ops_inventory": ops}


def emit_context_docs(shocks: dict[str, Shock]) -> pd.DataFrame:
    """Unstructured corroborating context — retrieved, never aggregated."""
    # Each document carries an explicit event window. Real incident, campaign
    # and deploy systems record start and end dates as fields; inferring an
    # exposure window from a ticket's creation timestamp plus a fixed pad is
    # guesswork, and a window that is wrong by a few days silently biases every
    # effect estimated from it.
    docs = [
        ("JIRA-4471", "2026-08-12T09:20:00", "2026-08-12", "2026-08-26", "EU", "deploy",
         "Checkout redesign v4.2 released to EU production. Canary skipped to "
         "meet the campaign date. Rollback artifact v4.1 retained."),
        ("ZD-88214", "2026-08-13T14:05:00", "2026-08-13", "2026-08-26", "EU", "support",
         "Payment failure complaints up 34% week on week. Customers report the "
         "card form clearing itself on validation error. All reports from EU."),
        ("JIRA-4489", "2026-08-14T11:40:00", "2026-08-14", "2026-08-26", "EU", "incident",
         "Elevated 5xx on /checkout/validate in EU cluster. Error rate 6.5% "
         "against a 0.4% baseline. Correlates with the v4.2 release window."),
        ("SCRAPE-2211", "2026-08-15T06:00:00", "2026-08-15", "2026-08-26", "EU", "competitor",
         "Competitor price index fell 12% on 14 comparable electronics SKUs. "
         "Promotion advertised as running to 26 August."),
        ("SCRAPE-2219", "2026-08-22T06:00:00", "2026-08-15", "2026-08-26", "EU", "competitor",
         "Competitor promotion confirmed still live. Price gap unchanged."),
        ("OPS-7702", "2026-08-19T08:15:00", "2026-08-19", "2026-08-23", "EU", "supply",
         "Stockout on 3 hero electronics SKUs across Rotterdam and Frankfurt "
         "fulfilment centres. Inbound container delayed at port. ETA 24 Aug."),
        ("FIN-3310", "2026-08-10T10:00:00", "2026-08-10", "2026-08-26", "EU", "budget",
         "Planned 30% reduction in EU paid acquisition budget takes effect "
         "today as part of the H2 efficiency programme. Approved by CFO."),
        ("MKT-5540", "2026-08-14T09:00:00", "2026-08-14", "2026-08-24", "EU", "campaign",
         "Accessories bundle promotion live 14-24 August across EU."),
        ("JIRA-4502", "2026-08-18T16:30:00", "2026-08-18", "2026-08-26", "EU", "finance",
         "Supplier landed cost increase of roughly 3% flows through from "
         "18 August on new EU purchase orders. Not yet reflected in SAP."),
        ("DQ-1180", "2026-08-20T03:00:00", "2026-08-20", "2026-08-26", "EU", "data_quality",
         "Partial load failure on the EU discount extract. Approximately 18% "
         "of rows written with null discount_inr from 20 August. Backfill "
         "not yet scheduled."),
        ("OPS-7688", "2026-08-17T06:00:00", "2026-08-17", "2026-08-26", "GLOBAL", "data_quality",
         "SAP IBP weekly stock export has not completed since 17 August. "
         "Pipeline owner on leave. Downstream margin reporting is stale."),
        ("MKT-5561", "2026-07-13T09:00:00", "2026-07-13", "2026-08-26", "EU", "launch",
         "Wearables category launched in EU and IN. No prior season of data. "
         "Use the audio accessories launch curve as the planning analogue."),
    ]
    return pd.DataFrame(docs, columns=["doc_id", "event_datetime", "event_start",
                                       "event_end", "region", "doc_type", "text"])


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main() -> None:
    print("CausIQ synthetic source generator")
    print("=" * 66)

    panels = build_panels()
    print(f"  series built                : {len(panels)}")

    print("  calibrating shock strengths to target contributions ...")
    shocks = calibrate(panels)
    for n in SHOCK_NAMES:
        print(f"    {n:<20} strength = {shocks[n].strength:.4f}")

    contrib, expected, actual = shapley_contributions(
        panels, shocks, ANALYSIS_REGION, ANALYSIS_START, ANALYSIS_END
    )

    print()
    print(f"  EU week {ANALYSIS_START.date()} .. {ANALYSIS_END.date()}")
    print(f"    expected (no shocks)      : Rs {expected/1e7:,.3f} Cr")
    print(f"    actual   (all shocks)     : Rs {actual/1e7:,.3f} Cr")
    print(f"    movement                  : {100*(actual-expected)/expected:+.2f}%")
    print()
    print("  Ground-truth Shapley contributions:")
    explained = 0.0
    for n in SHOCK_NAMES:
        pct = 100.0 * contrib[n] / expected
        explained += pct
        print(f"    {n:<20} {pct:+6.2f}%   (target {TARGET_CONTRIB_PCT[n]:+.2f}%)")
    print(f"    {'-- explained --':<20} {explained:+6.2f}%")

    sources = emit_sources(panels, shocks)
    ctx = emit_context_docs(shocks)

    for name, df in sources.items():
        path = DATA_DIR / f"{name}.parquet"
        df.to_parquet(path, index=False)
        print(f"  wrote {name:<14} {len(df):>8,} rows -> {path.name}")
    ctx.to_parquet(DATA_DIR / "ctx_docs.parquet", index=False)
    print(f"  wrote {'ctx_docs':<14} {len(ctx):>8,} rows -> ctx_docs.parquet")

    truth = {
        "generated_at": TODAY.isoformat(),
        "seed": SEED,
        "attribution_method": "exact Shapley over 2^5 counterfactual worlds",
        "note": (
            "Noise arrays are fixed across all counterfactual evaluations, so "
            "toggling a shock changes the outcome only through that shock's "
            "causal pathway."
        ),
        "analysis_window": {
            "kpi": "net_revenue",
            "region": ANALYSIS_REGION,
            "start": ANALYSIS_START.date().isoformat(),
            "end": ANALYSIS_END.date().isoformat(),
        },
        "expected_revenue_inr": expected,
        "actual_revenue_inr": actual,
        "movement_pct": 100.0 * (actual - expected) / expected,
        "contributions_pct": {n: 100.0 * contrib[n] / expected for n in SHOCK_NAMES},
        "contributions_inr": {n: contrib[n] for n in SHOCK_NAMES},
        "shock_strengths": {n: shocks[n].strength for n in SHOCK_NAMES},
        "shock_labels": {n: shocks[n].label for n in SHOCK_NAMES},
        "mediation_note": (
            "stockout and competitor_promo act on BOTH sessions and conversion. "
            "A correlational ranking will over-attribute to marketing_cut because "
            "total sessions fell for three different reasons."
        ),
        "planted_defects": {
            "ops_inventory_last_load": "2026-08-17 (240h stale vs 180h SLA)",
            "wh_sales_discount_null_rate_eu_from_2026_08_20": 0.18,
            "wearables_history_weeks": 6,
            "eu_landed_cost_increase_from_2026_08_18_pct": 3.1,
        },
    }
    tp = DATA_DIR.parent / "ground_truth.json"
    tp.write_text(json.dumps(truth, indent=2))
    print(f"\n  ground truth -> {tp}")
    print("=" * 66)


if __name__ == "__main__":
    main()
