"""
RETRIEVE — pull corroborating business context from unstructured sources.

Retrieval plays two distinct roles here, and keeping them separate matters:

1. QUANTITATIVE. Documents supply exposure windows -- the exact dates a
   stockout ran, when a promotion started. Those become regressors in the
   causal models (see challenge.py). This is retrieval feeding STATISTICS.

2. QUALITATIVE. Documents corroborate or contradict a statistical finding. A
   confirmed conversion drop that coincides with a deploy ticket AND a spike in
   payment complaints is better evidenced than the same drop with no
   surrounding narrative. This feeds the CONFIDENCE score, not the estimate.

What retrieval never does is produce a number that reaches a user. A support
ticket saying "complaints up 34%" is evidence that something happened; it is
not a measurement of anything, and the engine does not treat it as one.

BM25 is used deliberately over embeddings. On a corpus of a few hundred
operational documents, exact term matching on identifiers like SKU codes,
ticket numbers and region names outperforms semantic similarity, needs no
model or vector store, and every score is inspectable. Cost and latency are
effectively zero, which matters for the runtime budget.
"""

from __future__ import annotations

import math
import re
from collections import Counter
from dataclasses import dataclass
from typing import Any

import pandas as pd

_TOKEN = re.compile(r"[a-z0-9]+")


def _tok(text: str) -> list[str]:
    return _TOKEN.findall(text.lower())


@dataclass
class RetrievedDoc:
    doc_id: str
    doc_type: str
    region: str
    event_start: str
    event_end: str
    text: str
    score: float
    matched_terms: list[str]

    def as_dict(self) -> dict[str, Any]:
        return dict(self.__dict__)

    def citation(self) -> str:
        return f"{self.doc_id} ({self.doc_type}, {self.event_start})"


class BM25:
    """Standard BM25 with the usual k1/b. Small enough to read end to end."""

    def __init__(self, corpus: list[list[str]], k1: float = 1.5, b: float = 0.75):
        self.k1, self.b = k1, b
        self.corpus = corpus
        self.n = len(corpus)
        self.avgdl = sum(len(d) for d in corpus) / max(self.n, 1)
        self.tf = [Counter(d) for d in corpus]
        df: Counter = Counter()
        for d in corpus:
            df.update(set(d))
        self.idf = {
            t: math.log(1 + (self.n - c + 0.5) / (c + 0.5)) for t, c in df.items()
        }

    def score(self, query: list[str], i: int) -> tuple[float, list[str]]:
        tf, dl = self.tf[i], len(self.corpus[i])
        total, matched = 0.0, []
        for t in query:
            f = tf.get(t, 0)
            if not f:
                continue
            idf = self.idf.get(t, 0.0)
            denom = f + self.k1 * (1 - self.b + self.b * dl / self.avgdl)
            total += idf * (f * (self.k1 + 1)) / denom
            matched.append(t)
        return total, matched


class ContextIndex:
    def __init__(self, docs: pd.DataFrame):
        self.docs = docs.reset_index(drop=True)
        blobs = (self.docs["doc_type"].astype(str) + " "
                 + self.docs["region"].astype(str) + " "
                 + self.docs["text"].astype(str))
        self.bm25 = BM25([_tok(b) for b in blobs])

    def search(self, query: str, top_k: int = 5,
               region: str | None = None,
               within: tuple[str, str] | None = None) -> list[RetrievedDoc]:
        q = _tok(query)
        out: list[RetrievedDoc] = []
        for i, row in self.docs.iterrows():
            # Filters applied BEFORE scoring: a document from another region or
            # outside the window is not weak evidence, it is irrelevant, and
            # letting it compete on text similarity is how spurious citations
            # end up attached to findings.
            if region and row["region"] not in (region, "GLOBAL"):
                continue
            if within:
                s, e = pd.Timestamp(within[0]), pd.Timestamp(within[1])
                if pd.Timestamp(row["event_end"]) < s or pd.Timestamp(row["event_start"]) > e:
                    continue
            sc, matched = self.bm25.score(q, i)
            if sc <= 0:
                continue
            out.append(RetrievedDoc(
                doc_id=row["doc_id"], doc_type=row["doc_type"], region=row["region"],
                event_start=str(row["event_start"]), event_end=str(row["event_end"]),
                text=row["text"], score=round(float(sc), 3), matched_terms=matched,
            ))
        out.sort(key=lambda d: d.score, reverse=True)
        return out[:top_k]


def build_index(wh) -> ContextIndex:
    return ContextIndex(wh.q("SELECT * FROM raw_ctx_docs", label="ctx_docs"))


# Query terms per driver. Kept in code rather than generated by an LLM so that
# retrieval is reproducible run to run -- an LLM-written query would make the
# evidence trail non-deterministic for no benefit on a corpus this size.
DRIVER_QUERIES = {
    "checkout_experience": "checkout release deploy payment failure error rollback",
    "in_stock_rate": "stockout inventory availability warehouse delayed container",
    "competitor_price": "competitor price cut promotion scrape discount",
    "marketing_spend": "budget paid acquisition marketing spend reduction",
    "discount_depth": "promotion campaign bundle discount",
}


def corroborate(index: ContextIndex, driver: str, region: str,
                window: tuple[str, str], top_k: int = 3) -> list[RetrievedDoc]:
    q = DRIVER_QUERIES.get(driver, driver.replace("_", " "))
    return index.search(q, top_k=top_k, region=region, within=window)
